console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true

[secondary_prompt]
  template = '❯❯ '
  foreground = 'magenta'
  background = 'transparent'

[transient_prompt]
  template = '❯ '
  background = 'transparent'
  foreground_templates = ['{{if gt .Code 0}}red{{end}}', '{{if eq .Code 0}}magenta{{end}}']

[[blocks]]
  type = 'prompt'
  alignment = 'left'

  [[blocks.segments]]
    template = "\uf303  {{ .UserName }} on {{ .Path }}"
    foreground = 'blue'
    background = 'transparent'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      style = 'full'

  [[blocks.segments]]
    template = " \uf126 {{ .HEAD }}{{ if or (.Working.Changed) (.Staging.Changed) }} *{{end}} <cyan>{{ if gt .Behind 0 }}\U000f0310{{end}}{{ if gt .Ahead 0 }}\U000f031d{{end}}</>"
    foreground = 'p:grey'
    background = 'transparent'
    type = 'git'
    style = 'plain'

    [blocks.segments.properties]
      branch_icon = ''
      cache_duration = 'none'
      commit_icon = '@'
      fetch_status = true

[[blocks]]
  type="prompt"
  alignment="right"

  [[blocks.segments]]
    template = '{{ if .Venv }}({{ .Venv }}){{ end }} '
    foreground = 'cyan'
    powerline_symbol = "\ue0b0"
    background = 'transparent'
    type = 'python'
    style = 'plain'

    [blocks.segments.properties]
      cache_duration = 'none'
      display_mode = 'environment'
      fetch_virtual_env = true
      home_enabled = true

  [[blocks.segments]]
    template = "\uf017  {{ .CurrentDate | date .Format }} "
    foreground = "blue"
    background = "transparent"
    type = "time"
    style = "plain"
    
    [blocks.segments.properties]
    time_format = "15:04:05"

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    
    template = '❯'
    background = 'transparent'
    type = 'text'
    style = 'plain'
    foreground_templates = ['{{if gt .Code 0}}red{{end}}', '{{if eq .Code 0}}magenta{{end}}']

    [blocks.segments.properties]
      cache_duration = 'none' 

